# Generated by Django 5.1.3 on 2024-12-03 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_cart_app', '0010_usercart_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaledProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('poduct_slug', models.CharField(blank=True, max_length=550, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_cart_app.usercart')),
            ],
        ),
    ]
