# Generated by Django 5.1.3 on 2024-12-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saled_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledproducts',
            name='product_amount',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
