# Generated by Django 5.1.3 on 2024-12-04 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saled_products', '0002_alter_saledproducts_product_amount'),
        ('user_cart_app', '0010_usercart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledproducts',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_cart_app.usercart'),
        ),
    ]
