# Generated by Django 5.1.3 on 2024-12-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saled_products', '0003_alter_saledproducts_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledproducts',
            name='product_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
