# Generated by Django 5.1.3 on 2024-12-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saled_products', '0004_alter_saledproducts_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledproducts',
            name='poduct_slug',
        ),
    ]
