# Generated by Django 5.1.3 on 2024-11-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
