# Generated by Django 5.1.3 on 2024-11-25 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_alter_products_slug'),
        ('user_cart_app', '0002_usercart_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_cart_app.usercart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.products')),
            ],
        ),
    ]
