# Generated by Django 5.1.3 on 2024-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart_app', '0003_alter_usercart_product_amount_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
