# Generated by Django 5.1.3 on 2024-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_specialproducts'),
        ('user_cart_app', '0004_usercart_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='usercart',
            name='product_name',
            field=models.ManyToManyField(to='products_app.products'),
        ),
    ]
