# Generated by Django 5.1.3 on 2024-11-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_specialproducts'),
        ('user_cart_app', '0005_remove_usercart_product_name_usercart_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='usercart',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.products'),
        ),
    ]
