# Generated by Django 5.1.3 on 2024-12-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart_app', '0007_usercart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='slug',
        ),
    ]
