# Generated by Django 5.1.3 on 2024-12-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_specialproducts'),
        ('user_cart_app', '0008_remove_usercart_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='product_name_special',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.specialproducts'),
        ),
    ]
