# Generated by Django 5.1.3 on 2024-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart_app', '0009_usercart_product_name_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
