# Generated by Django 5.1.3 on 2024-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart_app', '0011_remove_usercart_product_name_special_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product_price',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
