# Generated by Django 5.1.3 on 2024-12-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cart_app', '0012_alter_usercart_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='slug',
        ),
    ]
