# Generated by Django 5.1.1 on 2024-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('product_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product_first_image', models.ImageField(upload_to='products/Images')),
                ('product_second_image', models.ImageField(upload_to='products/Images')),
                ('product_third_image', models.ImageField(blank=True, null=True, upload_to='products/Images')),
                ('prodcut_fourth_image', models.ImageField(blank=True, null=True, upload_to='products/Images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
