# Generated by Django 5.1.3 on 2024-11-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory_app', '0005_remove_catagory_cata_products'),
        ('products_app', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catagory_app.catagory'),
        ),
    ]
