# Generated by Django 5.1.3 on 2024-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cata_name', models.CharField(max_length=500, unique=True)),
                ('cata_products', models.ManyToManyField(to='products_app.products')),
            ],
        ),
    ]
