# Generated by Django 5.1.3 on 2024-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory_app', '0004_remove_catagory_cata_products_catagory_cata_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='cata_products',
        ),
    ]
