# Generated by Django 5.1.3 on 2024-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
